spring.application.name=insight-service
# service
server.port=8085
# usage service
usage.service.url=http://localhost:8083/api/v1/usage
# ai, ollama
spring.ai.ollama.chat.options.model=gemma4:12b
spring.ai.ollama.init.pull-model-strategy=never

