spring.application.name=device-service
# service port
server.port=8081
# MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/energy-db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none