spring.application.name=usage-service

# Service port
server.port=8083

# Kafka
spring.kafka.bootstrap-servers=localhost:9094

# kafka Producer
spring.kafka.template.default-topic=energy-alerts
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Kafka Consumer
spring.kafka.template.group-id=usage-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.panonit.kafka.event

# InfluxDB
influx.url=http://localhost:8086
influx.token=secret-token
influx.bucket=energy-bucket
influx.org=panonit

# User service
user.service.url=http://localhost:8080/api/v1/user

# Device service
device.service.url=http://localhost:8081/api/v1/device

# Actuator & Prometheus (scraped by Prometheus in docker-compose)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}