spring.application.name=usage-service
# service port
server.port=8083
# kafka
spring.kafka.bootstrap-servers=localhost:9094
# kafka-producer
spring.kafka.template.default-topic=energy-alerts
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
# kafka-consumer
spring.kafka.template.group-id=usage-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.panonit.kafka.event
# influxdb
influx.url=http://localhost:8086
influx.token=secret-token
influx.bucket=energy-bucket
influx.org=panonit
# user
user.service.url=http://localhost:8080/api/v1/user
# device
device.service.url=http://localhost:8081/api/v1/device
